name: proofBan
main: com.firestar.proofBan.main
version: 1
author: Firestar
commands:
  pban:
    description: Ban a player with proof
    usage: /<command> [playername] [world/reason] [reason]
    default: op
permissions:
  proof.ban:
    description: Execute Proof Bans
    default: op